<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <Platforms>x64</Platforms>
    <RootNamespace>StarMark.Tests</RootNamespace>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\StarMark.Abstractions\StarMark.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\StarMark.Integrations\StarMark.Integrations.csproj" />
    <ProjectReference Include="..\..\src\StarMark.Data\StarMark.Data.csproj" />
    <ProjectReference Include="..\..\src\StarMark.Core\StarMark.Core.csproj" />
  </ItemGroup>

</Project>